### ISSUE TITLE
dotnet ef database update 报错

### ISSUE THREAD

**Issue by wlsoftware** [SenparcCoreFramework/SCF#12]
The type initializer for 'Microsoft.AspNetCore.Http.SenparcHttpContext' threw an exception.   at Microsoft.AspNetCore.Http.SenparcHttpContext.get_ContentRootPath() in F:\WL.T\SCF-master\src\Senparc.Utility\SenparcHttpContext.cs:line 19
   at Microsoft.AspNetCore.Http.SenparcHttpContext.MapPath(String path) in F:\WL.T\SCF-master\src\Senparc.Utility\SenparcHttpContext.cs:line 51
   at Senparc.Core.Utility.Server.GetMapPath(String virtualPath) in F:\WL.T\SCF-master\src\Senparc.Utility\Senparc.Core.Utility\Server.cs:line 32
   at Senparc.Core.Utility.XmlDataContext.GetMapPath(String path) in F:\WL.T\SCF-master\src\Senparc.Core\Utility\XmlDataContext.cs:line 63
   at Senparc.Core.Utility.XmlDataContext.GetXElement(String path) in F:\WL.T\SCF-master\src\Senparc.Core\Utility\XmlDataContext.cs:line 53
   at Senparc.Core.Utility.XmlDataContext.GetXmlList[TEntity]() in F:\WL.T\SCF-master\src\Senparc.Core\Utility\XmlDataContext.cs:line 86
   at Senparc.Core.Config.SenparcDatabaseConfigs.<>c.<get_Configs>b__2_0() in F:\WL.T\SCF-master\src\Senparc.Core\Config\SenparcDatabaseConfigs.cs:line 23

**Comment by JeffreySu** [comment]
看一下你的 App_Data/Database下面有哪些文件？

**Comment by JeffreySu** [comment]
@wlsoftware 感谢！已经修正并发布到 master 分支，近期 SCF 底层进行了比较大的更新（见 https://github.com/SenparcCoreFramework/SCF/tree/Developer-RazorPage 分支），为进一步提高生产效率和进行 DDD 的优化实践，请关注！
